# Application configs
spring.application.name=SpringJavaFXGraal App

# Connection configs
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dev?reWriteBatchedInserts=true
spring.datasource.username=dev
spring.datasource.password=dev

# HikariCP configs
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000

logging.level.com.zaxxer.hikari.pool=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
